-- Kusina ni Mang Jose - Database Schema
-- Execute in Supabase SQL Editor

-- Table 1: Categories
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  slug TEXT,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table 2: Products
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT REFERENCES public.categories(id),
  name TEXT NOT NULL,
  description TEXT,
  price DECIMAL(10,2) NOT NULL,
  promotional_price DECIMAL(10,2),
  image TEXT,
  available BOOLEAN DEFAULT TRUE,
  featured BOOLEAN DEFAULT FALSE,
  best_seller BOOLEAN DEFAULT FALSE,
  stock INTEGER DEFAULT 999,
  sizes JSONB,
  add_ons JSONB,
  category_name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table 3: Users
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT DEFAULT 'customer',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table 4: Customers
CREATE TABLE IF NOT EXISTS public.customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id),
  phone TEXT,
  address TEXT,
  face_photo TEXT,
  verified_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table 5: Orders
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number TEXT NOT NULL UNIQUE,
  customer_id BIGINT REFERENCES public.customers(id),
  customer_name TEXT,
  mobile TEXT,
  email TEXT,
  address TEXT,
  order_type TEXT DEFAULT 'delivery',
  preferred_date DATE,
  preferred_time TEXT,
  order_status TEXT DEFAULT 'pending',
  payment_method TEXT,
  payment_status TEXT DEFAULT 'pending',
  subtotal DECIMAL(10,2),
  delivery_fee DECIMAL(10,2) DEFAULT 50,
  discount DECIMAL(10,2) DEFAULT 0,
  total DECIMAL(10,2),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table 6: Order Items
CREATE TABLE IF NOT EXISTS public.order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.products(id),
  product_name TEXT,
  quantity INTEGER DEFAULT 1,
  price DECIMAL(10,2),
  image TEXT,
  options JSONB,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table 7: Promotions
CREATE TABLE IF NOT EXISTS public.promotions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  discount_type TEXT,
  discount_amount DECIMAL(10,2),
  minimum_order DECIMAL(10,2),
  start_date DATE,
  end_date DATE,
  usage_limit INTEGER,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table 8: Settings
CREATE TABLE IF NOT EXISTS public.settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key_name TEXT NOT NULL UNIQUE,
  value_text TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert default categories
INSERT INTO public.categories (name, slug, description) VALUES
('Main Dishes', 'main-dishes', 'Delicious main courses'),
('Appetizers', 'appetizers', 'Start your meal with these'),
('Beverages', 'beverages', 'Refreshing drinks'),
('Desserts', 'desserts', 'Sweet treats'),
('Combo Meals', 'combo-meals', 'Value for money'),
('Sides', 'sides', 'Perfect side dishes')
ON CONFLICT (name) DO NOTHING;

-- Insert sample products
INSERT INTO public.products (category_id, name, description, price, image, available) VALUES
(1, 'Adobo Chicken', 'Tender chicken in savory adobo sauce', 250.00, 'https://via.placeholder.com/200?text=Adobo', TRUE),
(1, 'Sinigang na Baboy', 'Pork ribs in tangy tamarind broth', 280.00, 'https://via.placeholder.com/200?text=Sinigang', TRUE),
(2, 'Lumpia Shanghai', 'Crispy fried spring rolls', 120.00, 'https://via.placeholder.com/200?text=Lumpia', TRUE),
(2, 'Chicharong Baboy', 'Crispy pork belly', 150.00, 'https://via.placeholder.com/200?text=Chicharong', TRUE),
(3, 'Calamansi Juice', 'Fresh local lemon juice', 60.00, 'https://via.placeholder.com/200?text=Calamansi', TRUE),
(3, 'Iced Tea', 'Refreshing iced tea', 50.00, 'https://via.placeholder.com/200?text=IcedTea', TRUE),
(4, 'Leche Flan', 'Creamy caramel custard', 80.00, 'https://via.placeholder.com/200?text=LecheFlan', TRUE),
(5, 'Party Combo', 'Meal for 4 people', 500.00, 'https://via.placeholder.com/200?text=Combo', TRUE)
ON CONFLICT DO NOTHING;

-- Insert default settings
INSERT INTO public.settings (key_name, value_text) VALUES
('business_name', 'Kusina ni Mang Jose'),
('delivery_fee', '50'),
('minimum_order', '100'),
('contact_number', '09171234567'),
('email', 'info@kusina.ph'),
('address', 'Manila, Philippines')
ON CONFLICT (key_name) DO NOTHING;

-- Enable RLS (Row Level Security)
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promotions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- Create policies for public read access
CREATE POLICY "Allow public read on categories" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Allow public read on products" ON public.products FOR SELECT USING (available = true);
CREATE POLICY "Allow public read on settings" ON public.settings FOR SELECT USING (true);

COMMIT;
